#OPENAI_API_KEY = "<ENTER_YOUR_OPENAI_API_KEY>"
OPENAI_API_KEY = "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"

#MONGODB_USERNAME = "<ENTER_YOUR_USERNAME>"
MONGODB_USERNAME = "arivolit"
#MONGODB_USERNAME = ""

#MONGODB_USER_PASSWORD = "<ENTER_YOUR_USER_PASSWORD>"
MONGODB_USER_PASSWORD = "arivolit123"
#MONGODB_USER_PASSWORD = ""

#MONGODB_CLUSTER_HOSTNAME = "<ENTER_YOUR_MONGODB_CLUSTER_HOSTNAME>"
MONGODB_CLUSTER_HOSTNAME = "mongodbcluster0.bjmkbwc.mongodb.net"
#MONGODB_CLUSTER_HOSTNAME = ""

MONGODB_CLUSTER_DATABASE_NAME = "vectorsdb"
#MONGODB_CLUSTER_DATABASE_NAME = ""

MONGODB_DATABASE_GAMES_COLLECTION_NAME = "vectors"
#MONGODB_DATABASE_GAMES_COLLECTION_NAME = ""

MONGODB_DATABASE_CHAT_HISTORY_COLLECTION_NAME = "chat_history"
#MONGODB_DATABASE_CHAT_HISTORY_COLLECTION_NAME = ""
